# Generated by Django 5.2.7 on 2025-11-13 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_constituency_campaign_issue_pollingbooth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='State code (e.g., DL, MH, UP)', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organization/Party', 'verbose_name_plural': 'Organizations/Parties'},
        ),
        migrations.AddField(
            model_name='organization',
            name='party_color',
            field=models.CharField(blank=True, help_text='Party Color (Hex code)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='party_name',
            field=models.CharField(blank=True, help_text='Political Party Name (e.g., BJP, Congress)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='party_symbol',
            field=models.CharField(blank=True, help_text='Party Symbol', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_booth',
            field=models.ForeignKey(blank=True, help_text='Polling booth assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='api.pollingbooth'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_constituency',
            field=models.ForeignKey(blank=True, help_text='Constituency assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='api.constituency'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('state_admin', 'State Admin'), ('zone_admin', 'Zone/Region Admin'), ('district_admin', 'District Admin'), ('constituency_admin', 'Constituency Admin'), ('booth_admin', 'Booth/Field Admin'), ('analyst', 'War Room Analyst')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Political party this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('state_admin', 'State Admin'), ('zone_admin', 'Zone/Region Admin'), ('district_admin', 'District Admin'), ('constituency_admin', 'Constituency Admin'), ('booth_admin', 'Booth/Field Admin'), ('analyst', 'War Room Analyst')], default='analyst', max_length=25),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_district',
            field=models.ForeignKey(blank=True, help_text='District assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='api.district'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_state',
            field=models.ForeignKey(blank=True, help_text='State assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='api.state'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='api.state')),
            ],
            options={
                'verbose_name': 'Zone/Region',
                'verbose_name_plural': 'Zones/Regions',
                'ordering': ['state', 'name'],
                'unique_together': {('state', 'name')},
            },
        ),
        migrations.AddField(
            model_name='district',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.zone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_zone',
            field=models.ForeignKey(blank=True, help_text='Zone assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='api.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('zone', 'name')},
        ),
    ]
