# Generated by Django 5.2.7 on 2025-11-20 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_district_state_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='district_ref',
            field=models.ForeignKey(blank=True, help_text='District this constituency belongs to (ForeignKey)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='api.district'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='state_ref',
            field=models.ForeignKey(blank=True, help_text='State this constituency belongs to (ForeignKey)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='api.state'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='zone_ref',
            field=models.ForeignKey(blank=True, help_text='Zone/Region this constituency belongs to (ForeignKey)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='api.zone'),
        ),
        migrations.AddIndex(
            model_name='constituency',
            index=models.Index(fields=['district_ref'], name='api_constit_distric_1684b4_idx'),
        ),
        migrations.AddIndex(
            model_name='constituency',
            index=models.Index(fields=['zone_ref'], name='api_constit_zone_re_597d53_idx'),
        ),
        migrations.AddIndex(
            model_name='constituency',
            index=models.Index(fields=['state_ref'], name='api_constit_state_r_7ca5fa_idx'),
        ),
    ]
