# Generated by Django 5.2.7 on 2025-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_constituency_fk_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='center_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Map center latitude coordinate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='center_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Map center longitude coordinate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='has_geojson',
            field=models.BooleanField(default=False, help_text='Whether GeoJSON file exists for this state'),
        ),
        migrations.AddField(
            model_name='state',
            name='zoom_level',
            field=models.DecimalField(decimal_places=1, default=6.5, help_text='Default map zoom level', max_digits=3),
        ),
    ]
