# Generated by Django 5.2.7 on 2025-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_map_config_to_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='landing_page_config',
            field=models.JSONField(blank=True, default=dict, help_text='Custom landing page configuration (hero, colors, logo, etc.)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(blank=True, help_text="Unique subdomain for multi-tenant landing page (e.g., 'tvk' for tvk.pulseofpeople.com)", max_length=100, null=True, unique=True),
        ),
    ]
