# Generated by Django 5.2.7 on 2025-11-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_multi_tenant_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='landing_page_config',
            field=models.JSONField(blank=True, default=dict, help_text='Custom landing page configuration (hero, features, stats, etc.)'),
        ),
    ]
